# Generated by Django 4.1.3 on 2022-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='shop 1', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
